version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tigerbeetle:
    image: tigerbeetle/tigerbeetle:latest
    ports:
      - "3000:3000"
    command: tigerbeetle start --addresses=0.0.0.0:3000
    volumes:
      - tigerbeetle_data:/var/lib/tigerbeetle
    healthcheck:
      test: ["CMD", "tigerbeetle", "status", "--addresses", "0.0.0.0:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      API_KEY: test-api-key-123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: transaction_db
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      TIGERBEETLE_CLUSTER_ID: 0
      TIGERBEETLE_HOST: tigerbeetle
      TIGERBEETLE_PORT: 3000
      LOG_LEVEL: info
      MIGRATION_ENABLED: true
      MIGRATION_DIRECTION: up
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      tigerbeetle:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  tigerbeetle_data:
