services:
  pgsql:
    image: postgis/postgis:14-3.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: pgsql
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.6-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle:latest
    container_name: tigerbeetle
    command: "start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle"
    volumes:
      - tigerbeetle_data:/data
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "tigerbeetle", "status", "--addresses", "0.0.0.0:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      API_KEY: test-api-key-123
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tx
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      TIGERBEETLE_CLUSTER_ID: 0
      TIGERBEETLE_HOST: tigerbeetle
      TIGERBEETLE_PORT: 3000
      LOG_LEVEL: info
      MIGRATION_ENABLED: true
      MIGRATION_DIRECTION: up
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      tigerbeetle:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
    name: redis_data
  tigerbeetle_data:
    name: tigerbeetle_data
